### PR TITLE
Assignment 1

### PR DESCRIPTION
**Pull request by vikramkatju**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Merging code in two different versions of the same file.

## What did you learn from the changes you have made?
The fact that merging does involve a manual component since I had to check for errors in the code of the file (with changes) made by the coworker.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
Initially I thought merging would be completely automated without my checking for errors in the file (with changes) made by the coworker

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
No particular challenges

## How were these changes tested?
By running the file (with changes) made by the collaborator on the bash terminal.

## A reference to a related issue in your repository (if applicable)
Not applicable

## Checklist
- [ Yes] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by pedram-aliniaye-asli** [comment]
You did a great job here!
A few things to notice:
1) Please keep the pull request open during the marking process, and then you can close or merge the request after the assignment gets marked.
2) The branch name should be `assignment` not `assignment-1`.
So please go ahead and do the modification and then let me know. Thanks!

**Comment by vikramkatju** [comment]
Hi Pedram, thank you for your comments. I have renamed the branch to assignment.

**Comment by anjali-deshpande-hub** [comment]
The assignment.sh file in 'main' branch should not have any of your code changes. Please change that well. Thanks! For help follow: https://uoft-dsi-certificates.slack.com/archives/C07VC7M4PTL/p1732596801781119

**Comment by vikramkatju** [comment]
Hi Anjali, I've fixed the main branch now. Thank you.

**Review by anjali-deshpande-hub — COMMENTED** [review]
Wonderful!! Your assignment has been marked complete.

**Comment by vikramkatju** [comment]
Thank you Anjali.

**Pull request merged**
